apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-bot
  namespace: dev
  labels:
    tier: backend
spec:
  selector:
    matchLabels:
      app: app-bot
      tier: backend
  replicas: 1
  template:
    metadata:
      namespace: dev
      labels:
        app: app-bot
        tier: backend
    spec:        
      containers:
      - name: app-bot
        image: bot:dev
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "500m"                 
